name         'sqmk-elasticsearch'
version      '0.0.1'
author       'Michael K. Squires'
license      'BSD'
summary      'Install and manage ElasticSearch.'
description  'Install and manage ElasticSearch.'
project_page 'https://github.com/sqmk/puppet-elasticsearch'
dependency   'maestrodev/wget', '>= 1.2.3'
dependency   'puppetlabs/java', '>= 1.0.1'
